In [1]:
!pip install -q datasets scikit-learn pandas pyarrow matplotlib

In [2]:
import ast
import json
import re
from collections import Counter

import pandas as pd
from datasets import load_dataset

VAL_URL = (
    "https://huggingface.co/datasets/"
    "EleutherAI/pile_val_test/resolve/main/val.jsonl"
)

# Load as a streaming dataset
stream = load_dataset(
    "json",
    data_files=VAL_URL,
    split="train",
    streaming=True
)

# Approximate randomization without loading everything
stream = stream.shuffle(seed=42, buffer_size=10_000)

In [3]:
def extract_source(meta):
    """Extract the Pile component name from metadata."""

    if isinstance(meta, dict):
        return meta.get("pile_set_name", "Unknown")

    if isinstance(meta, str):
        try:
            parsed = json.loads(meta)
        except (json.JSONDecodeError, TypeError):
            try:
                parsed = ast.literal_eval(meta)
            except (ValueError, SyntaxError):
                return "Unknown"

        if isinstance(parsed, dict):
            return parsed.get("pile_set_name", "Unknown")

    return "Unknown"


def clean_text(text, max_characters=3000):
    """Perform minimal cleaning and truncate long documents."""

    text = str(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:max_characters]

In [4]:
DOCUMENTS_PER_SOURCE = 400
MIN_CHARACTERS = 200
MAX_CHARACTERS = 3000
MAX_RECORDS_TO_SCAN = 200_000

rows = []
source_counts = Counter()

for record_number, example in enumerate(stream):

    if record_number >= MAX_RECORDS_TO_SCAN:
        break

    text = clean_text(
        example.get("text", ""),
        max_characters=MAX_CHARACTERS
    )

    if len(text) < MIN_CHARACTERS:
        continue

    source = extract_source(example.get("meta", {}))

    # Prevent large sources from dominating the sample
    if source_counts[source] >= DOCUMENTS_PER_SOURCE:
        continue

    rows.append({
        "text": text,
        "source": source
    })

    source_counts[source] += 1

df = pd.DataFrame(rows)

print("Number of documents:", len(df))
print("Number of sources:", df["source"].nunique())

display(
    df["source"]
    .value_counts()
    .rename_axis("source")
    .reset_index(name="documents")
)

Number of documents: 6827
Number of sources: 22

               source  documents
0             Pile-CC        400
1      Wikipedia (en)        400
2       StackExchange        400
3    PubMed Abstracts        400
4        OpenWebText2        400
5      PubMed Central        400
6               ArXiv        400
7   USPTO Backgrounds        400
8      DM Mathematics        400
9              Github        400
10            FreeLaw        400
11      OpenSubtitles        400
12       NIH ExPorter        400
13         HackerNews        400
14       Enron Emails        400
15             Books3        279
16   YoutubeSubtitles        273
17           EuroParl        121
18         PhilPapers         58
19  Gutenberg (PG-19)         57
20        BookCorpus2         24
21         Ubuntu IRC         15

In [5]:
df.to_parquet("pile_sample.parquet", index=False)
df.to_csv("pile_sample.csv", index=False)

In [6]:
df = pd.read_parquet("pile_sample.parquet")

In [7]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

keyword_vectorizer = TfidfVectorizer(
    stop_words="english",
    lowercase=True,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.90,
    max_features=20_000,
    sublinear_tf=True
)

keyword_matrix = keyword_vectorizer.fit_transform(df["text"])
terms = np.array(keyword_vectorizer.get_feature_names_out())

print("TF-IDF matrix shape:", keyword_matrix.shape)

TF-IDF matrix shape: (6827, 20000)

In [8]:
mean_scores = np.asarray(keyword_matrix.mean(axis=0)).ravel()
top_indices = mean_scores.argsort()[::-1][:30]

overall_keywords = pd.DataFrame({
    "keyword": terms[top_indices],
    "tfidf_score": mean_scores[top_indices]
})

display(overall_keywords)

     keyword  tfidf_score
0       like     0.011378
1        new     0.011101
2       time     0.010605
3        let     0.010354
4         10     0.010153
5       just     0.009967
6        com     0.009814
7        use     0.009323
8       know     0.009012
9        don     0.008794
10     using     0.008205
11        12     0.007997
12    people     0.007927
13      used     0.007759
14      work     0.007721
15        11     0.007693
16      data     0.007531
17     right     0.007511
18      make     0.007187
19      good     0.007125
20       way     0.007030
21      need     0.006983
22      want     0.006969
23     years     0.006952
24  category     0.006867
25      http     0.006837
26        15     0.006720
27        ve     0.006666
28     court     0.006623
29      high     0.006403

In [9]:
def source_keywords(
    dataframe,
    matrix,
    vocabulary,
    top_n=15
):
    results = []

    for source in sorted(dataframe["source"].unique()):
        positions = np.where(
            dataframe["source"].to_numpy() == source
        )[0]

        source_scores = np.asarray(
            matrix[positions].mean(axis=0)
        ).ravel()

        top_positions = source_scores.argsort()[::-1][:top_n]

        for rank, position in enumerate(top_positions, start=1):
            results.append({
                "source": source,
                "rank": rank,
                "keyword": vocabulary[position],
                "score": source_scores[position]
            })

    return pd.DataFrame(results)


source_keyword_df = source_keywords(
    dataframe=df,
    matrix=keyword_matrix,
    vocabulary=terms,
    top_n=15
)

display(source_keyword_df.head(45))

         source  rank             keyword     score
0         ArXiv     1            abstract  0.037110
1         ArXiv     2              author  0.036096
2         ArXiv     3               title  0.035435
3         ArXiv     4        introduction  0.030646
4         ArXiv     5             quantum  0.024458
5         ArXiv     6               model  0.022172
6         ArXiv     7             physics  0.022138
7         ArXiv     8                 bib  0.021227
8         ArXiv     9              theory  0.019767
9         ArXiv    10              energy  0.019280
10        ArXiv    11          university  0.019249
11        ArXiv    12               paper  0.018843
12        ArXiv    13        bibliography  0.018800
13        ArXiv    14             systems  0.018508
14        ArXiv    15               field  0.018335
15  BookCorpus2     1          smashwords  0.099964
16  BookCorpus2     2                book  0.069429
17  BookCorpus2     3             chapter  0.068933
18  BookCorpus2     4            purchase  0.065041
19  BookCorpus2     5  smashwords edition  0.060878
20  BookCorpus2     6               ebook  0.056354
21  BookCorpus2     7     chapter chapter  0.053885
22  BookCorpus2     8                copy  0.050955
23  BookCorpus2     9           enjoyment  0.050587
24  BookCorpus2    10             edition  0.046473
25  BookCorpus2    11           copyright  0.045317
26  BookCorpus2    12  purchase purchased  0.045166
27  BookCorpus2    13        did purchase  0.045166
28  BookCorpus2    14  personal enjoyment  0.045166
29  BookCorpus2    15   licensed personal  0.045166
30       Books3     1                book  0.050449
31       Books3     2             chapter  0.043907
32       Books3     3           copyright  0.040024
33       Books3     4                isbn  0.033711
34       Books3     5            contents  0.033016
35       Books3     6               books  0.030823
36       Books3     7              author  0.029345
37       Books3     8                 978  0.028338
38       Books3     9           publisher  0.026561
39       Books3    10                _the  0.026511
40       Books3    11              rights  0.025370
41       Books3    12           published  0.024789
42       Books3    13                 new  0.024366
43       Books3    14             library  0.024299
44       Books3    15                york  0.024104

In [10]:
source_keyword_df[
    source_keyword_df["source"] == "ArXiv"
]

   source  rank       keyword     score
0   ArXiv     1      abstract  0.037110
1   ArXiv     2        author  0.036096
2   ArXiv     3         title  0.035435
3   ArXiv     4  introduction  0.030646
4   ArXiv     5       quantum  0.024458
5   ArXiv     6         model  0.022172
6   ArXiv     7       physics  0.022138
7   ArXiv     8           bib  0.021227
8   ArXiv     9        theory  0.019767
9   ArXiv    10        energy  0.019280
10  ArXiv    11    university  0.019249
11  ArXiv    12         paper  0.018843
12  ArXiv    13  bibliography  0.018800
13  ArXiv    14       systems  0.018508
14  ArXiv    15         field  0.018335

In [11]:
source_keyword_df.to_csv(
    "pile_keywords_by_source.csv",
    index=False
)

In [12]:
from sklearn.decomposition import NMF

NUMBER_OF_TOPICS = 15

nmf_model = NMF(
    n_components=NUMBER_OF_TOPICS,
    init="nndsvda",
    random_state=42,
    max_iter=400
)

document_topic_matrix = nmf_model.fit_transform(keyword_matrix)

print("Document-topic shape:", document_topic_matrix.shape)

Document-topic shape: (6827, 15)

In [13]:
def display_nmf_topics(model, feature_names, words_per_topic=12):
    topic_records = []

    for topic_number, component in enumerate(model.components_):
        top_positions = component.argsort()[::-1][:words_per_topic]
        topic_words = feature_names[top_positions]

        topic_records.append({
            "topic": topic_number,
            "keywords": ", ".join(topic_words)
        })

    return pd.DataFrame(topic_records)


topic_summary = display_nmf_topics(
    model=nmf_model,
    feature_names=terms,
    words_per_topic=12
)

display(topic_summary)

    topic                                           keywords
0       0  don, know, just, like, ll, right, think, ve, g...
1       1  let, suppose, let let, derivative, let derivat...
2       2  patients, study, treatment, clinical, disease,...
3       3  court, district, appellant, appeals, district ...
4       4  return, public, license, class, string, file, ...
5       5  enron, ect, hou, hou ect, cc, subject, ect ect...
6       6  book, chapter, copyright, books, isbn, york, n...
7       7  abstract, title, author, introduction, quantum...
8       8  que, la, en, se, el, para, por, es, una, como,...
9       9     11, 13, 12, 10, 14, 16, 15, 17, 22, 18, 19, 21
10     10  category, references, references category, ext...
11     11  com, http, https, www, http www, html, google,...
12     12  letters picked, picked replacement, prob, pick...
13     13  invention, relates, device, present invention,...
14     14  cells, cell, protein, expression, gene, protei...

In [14]:
df["topic"] = document_topic_matrix.argmax(axis=1)
df["topic_strength"] = document_topic_matrix.max(axis=1)

display(
    df[
        ["source", "topic", "topic_strength", "text"]
    ].head()
)

,source,topic,topic_strength,text
0,Pile-CC,4,0.051904,Data-BitStream-0.07 NAME VERSION version 0.03 ...
1,Wikipedia (en),10,0.072810,Thrombolite Thrombolites are ancient forms of ...
2,StackExchange,4,0.080004,Q: Use route as url in config with Symfony I u...
3,Pile-CC,2,0.028575,A mammoth and humans on the banks of the Marne...
4,PubMed Abstracts,14,0.033008,Synthetic polycation: polynucleotide interacti...

In [15]:
topic_counts = (
    df["topic"]
    .value_counts()
    .sort_index()
    .rename_axis("topic")
    .reset_index(name="documents")
)

display(topic_counts)

    topic  documents
0       0        868
1       1        204
2       2        827
3       3        462
4       4        590
5       5        320
6       6        501
7       7        593
8       8        236
9       9        254
10     10        354
11     11        556
12     12         27
13     13        548
14     14        487

In [16]:
source_topic_table = pd.crosstab(
    df["source"],
    df["topic"],
    normalize="index"
).round(3)

display(source_topic_table)

topic,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
source,,,,,,,,,,,,,,,
ArXiv,0.000,0.000,0.002,0.000,0.000,0.000,0.000,0.985,0.005,0.000,0.000,0.000,0.000,0.005,0.002
BookCorpus2,0.042,0.000,0.000,0.000,0.000,0.000,0.917,0.000,0.000,0.042,0.000,0.000,0.000,0.000,0.000
Books3,0.029,0.000,0.011,0.000,0.000,0.000,0.907,0.004,0.014,0.036,0.000,0.000,0.000,0.000,0.000
DM Mathematics,0.000,0.507,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.438,0.000,0.000,0.055,0.000,0.000
Enron Emails,0.045,0.000,0.018,0.008,0.022,0.778,0.012,0.005,0.002,0.015,0.000,0.065,0.000,0.030,0.000
EuroParl,0.008,0.000,0.041,0.017,0.000,0.000,0.017,0.000,0.901,0.008,0.000,0.000,0.000,0.008,0.000
FreeLaw,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Github,0.010,0.002,0.002,0.002,0.782,0.010,0.005,0.018,0.002,0.045,0.000,0.110,0.000,0.010,0.000
Gutenberg (PG-19),0.070,0.000,0.000,0.000,0.000,0.000,0.895,0.000,0.000,0.035,0.000,0.000,0.000,0.000,0.000
HackerNews,0.080,0.000,0.008,0.002,0.008,0.002,0.000,0.005,0.000,0.000,0.000,0.885,0.002,0.002,0.005
NIH ExPorter,0.000,0.000,0.408,0.000,0.000,0.000,0.000,0.015,0.000,0.000,0.000,0.000,0.000,0.008,0.570
OpenSubtitles,0.992,0.000,0.002,0.000,0.000,0.000,0.002,0.002,0.000,0.000,0.000,0.000,0.000,0.000,0.000
OpenWebText2,0.275,0.000,0.208,0.068,0.015,0.005,0.138,0.028,0.052,0.020,0.052,0.058,0.002,0.072,0.008
PhilPapers,0.017,0.000,0.052,0.000,0.000,0.000,0.207,0.500,0.172,0.017,0.017,0.000,0.000,0.017,0.000
Pile-CC,0.350,0.000,0.175,0.032,0.012,0.000,0.115,0.028,0.005,0.020,0.040,0.098,0.002,0.118,0.005
PubMed Abstracts,0.000,0.000,0.555,0.002,0.000,0.000,0.000,0.088,0.000,0.005,0.002,0.000,0.000,0.045,0.302
PubMed Central,0.000,0.000,0.560,0.000,0.000,0.000,0.008,0.070,0.000,0.032,0.000,0.005,0.000,0.018,0.308
StackExchange,0.042,0.000,0.008,0.002,0.630,0.002,0.010,0.098,0.008,0.010,0.002,0.135,0.005,0.045,0.002
USPTO Backgrounds,0.000,0.000,0.032,0.000,0.000,0.000,0.000,0.008,0.000,0.000,0.000,0.002,0.000,0.950,0.008
Ubuntu IRC,0.200,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.133,0.000,0.000,0.667,0.000,0.000,0.000
Wikipedia (en),0.002,0.000,0.018,0.022,0.002,0.000,0.098,0.018,0.008,0.008,0.782,0.000,0.000,0.038,0.005
YoutubeSubtitles,0.480,0.000,0.066,0.015,0.004,0.004,0.022,0.062,0.286,0.007,0.004,0.011,0.000,0.037,0.004

In [17]:
!pip install -q bertopic sentence-transformers umap-learn hdbscan

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 7.6 MB/s eta 0:00:00

In [18]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# Use a smaller sample
bertopic_df = df.sample(
    n=min(7000, len(df)),
    random_state=42
).copy()

# Further truncate texts to reduce embedding time
documents = bertopic_df["text"].str[:1500].tolist()

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    min_topic_size=30,
    calculate_probabilities=False,
    low_memory=True,
    verbose=True
)

topics, probabilities = topic_model.fit_transform(documents)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2026-07-21 07:01:41,698 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/214 [00:00<?, ?it/s]

2026-07-21 07:02:01,923 - BERTopic - Embedding - Completed ✓
2026-07-21 07:02:01,924 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-07-21 07:02:34,358 - BERTopic - Dimensionality - Completed ✓
2026-07-21 07:02:34,360 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-07-21 07:02:34,595 - BERTopic - Cluster - Completed ✓
2026-07-21 07:02:34,601 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-07-21 07:02:36,256 - BERTopic - Representation - Completed ✓

In [19]:
topic_info = topic_model.get_topic_info()
display(topic_info.head(20))

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1366,-1_the_to_is_and,"[the, to, is, and, of, in, what, it, that, for]","[Ask HN: Review my coming soon page, SettleIt...."
1,0,1293,0_of_and_the_in,"[of, and, the, in, to, with, is, for, that, by]",[The objectives of this Project are two-fold. ...
2,1,702,1_the_this_to_import,"[the, this, to, import, if, class, license, pu...",[Q: matlab - what is the equivalent of null / ...
3,2,456,2_court_of_the_district,"[court, of, the, district, for, and, appellant...",[991 F.2d 791 NOTICE: Fourth Circuit I.O.P. 36...
4,3,439,3_the_of_in_we,"[the, of, in, we, and, is, to, for, that, abst...",[--- abstract: 'The dynamical stability of non...
5,4,414,4_you_it_me_to,"[you, it, me, to, my, that, we, what, re, don]","[""Help!"" ""Help!"" "" Somebody help me!"" "" Oh my ..."
6,5,398,5_the_chapter_of_and,"[the, chapter, of, and, in, by, book, to, this...",[Begin Reading Table of Contents About the Aut...
7,6,380,6_enron_ect_hou_to,"[enron, ect, hou, to, com, subject, the, 2001,...",[calendar/mtg folder ----- Forwarded by Steven...
8,7,364,7_the_of_to_and,"[the, of, to, and, in, is, or, invention, an, ...",[1. Field of the Invention The present inventi...
9,8,205,8_to_it_the_and,"[to, it, the, and, that, you, for, is, of, com]",[12 things I learned from pitching VCs this pa...
10,9,129,9_category_the_he_in,"[category, the, he, in, players, team, to, at,...","[Jerry Gill Jeremy Morley ""Jerry"" Gill (born 8..."
11,10,128,10_the_to_of_in,"[the, to, of, in, and, that, on, president, tr...",[Total War for the Hearts and Minds of America...
12,11,117,11_let_derivative_solve_suppose,"[let, derivative, solve, suppose, be, wrt, det...",[at is y(h)? 5 Let c be -2*(1/(-2))/(-1). Let ...
13,12,97,12_what_base_is_calculate,"[what, base, is, calculate, divided, prime, re...","[ase 9, what is -688 + 5? -683 In base 7, what..."
14,13,86,13_de_que_la_el,"[de, que, la, el, en, para, se, los, un, da]",[Índice Cubierta Portadilla ADVERTENCIA SOBRE ...
15,14,52,14_and_the_you_to,"[and, the, you, to, it, in, with, of, or, that]","[For my grandparents, and for JMU: the Tall Ma..."
16,15,51,15_az_és_ir_ja,"[az, és, ir, ja, za, je, es, sebebi, sensin, p...",[Čas za vprašanja (vprašanja Svetu) Predsednik...
17,16,44,16_the_to_and_hotel,"[the, to, and, hotel, of, in, city, is, that, ...","[Holidays in Paris, France Book Flight+Hotel P..."
18,17,37,17_och_att_för_det,"[och, att, för, det, som, av, de, om, har, den]",[Anföranden på en minut om frågor av politisk ...
19,18,35,18_album_band_was_the,"[album, band, was, the, and, released, songs, ...",[Amplifier (Amplifier album) Amplifier is the ...

In [20]:
topic_model.get_topic(0)

[('of', np.float64(0.04161192565061939)),
 ('and', np.float64(0.03923545837345143)),
 ('the', np.float64(0.035775828558398455)),
 ('in', np.float64(0.033587942874474065)),
 ('to', np.float64(0.02625117119510819)),
 ('with', np.float64(0.020257249043064283)),
 ('is', np.float64(0.017130677594756703)),
 ('for', np.float64(0.01650505997187195)),
 ('that', np.float64(0.014942528245137827)),
 ('by', np.float64(0.014484591812792953))]

In [21]:
bertopic_df["topic"] = topics
bertopic_df.to_csv(
    "pile_bertopic_results.csv",
    index=False
)